"""
Step 8: Create Persistent Chroma Vector Store.

LangChain / RAG Concept:
------------------------
What is Chroma?
Chroma is an open-source vector database built specifically for AI applications.
It stores:
  1. The text chunk (document content).
  2. The chunk's metadata (source filename, page number).
  3. The vector embedding generated by the embedding model.

Why Persistent?
By setting `persist_directory="data/chroma_db"`, Chroma writes its SQLite index
and HNSW vector files directly to your hard drive.
Benefits:
  - You only embed course materials ONCE.
  - When a student asks questions, the app connects directly to the saved database
    instantly, without waiting to re-read or re-embed the PDF!
"""

import os
import shutil
from langchain_community.document_loaders import PyPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_ollama import OllamaEmbeddings
from langchain_chroma import Chroma

CHROMA_DIR = os.path.join("data", "chroma_db")
COLLECTION_NAME = "course_material"
EMBED_MODEL = "nomic-embed-text"

def build_vector_store(pdf_path: str, persist_dir: str = CHROMA_DIR):
    print(f"1. Loading course document: {pdf_path}")
    loader = PyPDFLoader(pdf_path)
    docs = loader.load()
    
    print(f"2. Splitting into chunks...")
    splitter = RecursiveCharacterTextSplitter(chunk_size=250, chunk_overlap=50)
    chunks = splitter.split_documents(docs)
    print(f"   Created {len(chunks)} chunks.")
    
    print(f"3. Connecting to Ollama Embeddings ({EMBED_MODEL})...")
    embeddings = OllamaEmbeddings(model=EMBED_MODEL)
    
    # Clean any old test artifacts to build fresh
    if os.path.exists(persist_dir):
        print(f"   Cleaning existing Chroma directory for fresh build: {persist_dir}")
        shutil.rmtree(persist_dir)
        
    print(f"4. Generating embeddings and storing in Chroma at: {persist_dir} ...")
    vector_store = Chroma.from_documents(
        documents=chunks,
        embedding=embeddings,
        persist_directory=persist_dir,
        collection_name=COLLECTION_NAME
    )
    
    return vector_store, embeddings

def verify_persistence(persist_dir: str, embeddings):
    print(f"\n5. Verifying persistence by re-opening Chroma from disk...")
    
    loaded_store = Chroma(
        persist_directory=persist_dir,
        embedding_function=embeddings,
        collection_name=COLLECTION_NAME
    )
    
    stored_data = loaded_store.get()
    total_stored = len(stored_data["ids"])
    print(f"   -> Successfully loaded vector store from disk!")
    print(f"   -> Total embedded chunks stored: {total_stored}")
    
    # Inspect first stored chunk metadata
    if total_stored > 0:
        sample_meta = stored_data["metadatas"][0]
        print(f"   -> Sample stored metadata: {sample_meta}")
        
    return total_stored

def main():
    pdf_path = os.path.join("data", "sample_course.pdf")
    
    if not os.path.exists(pdf_path):
        print(f"PDF not found at {pdf_path}. Running generator first...")
        from create_sample_pdf import create_sample_course_pdf
        create_sample_course_pdf(pdf_path)
        
    vector_store, embeddings = build_vector_store(pdf_path)
    count = verify_persistence(CHROMA_DIR, embeddings)
    
    assert count > 0, "Vector store did not persist any documents!"
    print("\nStep 8 is COMPLETE: Persistent Chroma vector store created and verified!")

if __name__ == "__main__":
    main()